### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by jksalva42** [msnx/KernelSU-Pixel4XL#1]
Sir can u plz make kernelSU for Android 11-12  pixel 4/xl bcos some apps are crashing in a13...
By the way thnx for your work

**Comment by msnx** [comment]
Hi man.It's a pity that i have only one pixel4xl device(a13) for kernelsu testing.Maybe you can refer to the Documentation(https://source.android.com/docs/setup/build/building-kernels) to complete you own bootimg build for a11-12 .

**Comment by jksalva42** [comment]
> Hi man.It's a pity that i have only one pixel4xl device(a13) for kernelsu testing.Maybe you can refer to the Documentation(https://source.android.com/docs/setup/build/building-kernels) to complete you own bootimg build for a11-12 .

Bro i don't know how to do can u help me for this... And i need your telegram username... Can u pls help me

**Comment by msnx** [comment]
Try to flash boot.img follow repository https://github.com/a2504028411/kernelsu-pixel4xl-android12,maybe this will help u.

**Comment by jksalva42** [comment]
Bro is this your fork or another one?

**Comment by msnx** [comment]
This is another contributor's repository.
