### ISSUE TITLE
THIS REPO BREAKS GPL

### ISSUE THREAD

**Issue by REV3NT3CH** [msnx/KernelSU-Pixel4XL#12]
The source you have provided does NOT keep authored commit history in tact and is in direct violation of GPL. If this is not corrected within the next 48 hrs this repository will be reported and will likely be issued a DMCA.

**Comment by msnx** [comment]
Thanks for your reminder.I will correct this repo's license.

**Comment by REV3NT3CH** [comment]
Bro. Do you even understand what you are needing to do? Deleting the e files you have is even in more violation. Go on any other kernel source for 4/4xl and look at commits. Where you have yours shows you as the author of everything and completely ignores all the history of authors of the commits made prior... especially by Google themselves and others. This has jack to do with "license" files.

**Comment by REV3NT3CH** [comment]
Anyways....this source has been reported to google developers for the failure of uploaded proper commit history and licenses to do so. If you don't understand how to do this it isn't hard to ask for help of knowledge to do so. But it's doing things like this that make the source not only in violation, but sketchy for possible malware. Not to mention it gives a bad look to the open source developers and why source has become more proprietary.

**Comment by msnx** [comment]
Bro,i just recomitted the pixel4 kernel source code for this repository.It is a pity that the code submission failed several times due to network problems.Now the authored commit history maybe avaliable.
