### ISSUE TITLE
build ID: TP1A.221005.002  support ?

### ISSUE THREAD

**Issue by ohyeah521** [msnx/KernelSU-Pixel4XL#15]
`TP1A.221005.002 | android-13.0.0_r7 | Android13 | Pixel 4、Pixel 4a、Pixel 4a (5G)、Pixel 4 XL、Pixel 5、Pixel 5a (5G)、Pixel 6、Pixel 6 Pro | 2022-10-05`

**Comment by msnx** [comment]
Support Pixel 4/4XL.

**Comment by ohyeah521** [comment]
thanks
