### ISSUE TITLE
我是pixel3用户，我会编译内核。但我不知道改哪些文件。可以把你改的哪些文件发一下吗，我参考着改。

### ISSUE THREAD

**Issue by hqweb** [msnx/KernelSU-Pixel4XL#2]

**Comment by jksalva42** [comment]
For pixel 3 alrdy ksu available...

**Comment by msnx** [comment]
pixel4xl内核编译前修改了android-kernel/private/msm-google/arch/arm64/configs/floral_defconfig文件，添加如下代码开启KPROBES：
CONFIG_KPROBES=y
CONFIG_HAVE_KPROBES=y
CONFIG_KPROBE_EVENTS=y
