### ISSUE TITLE
Pixel 4（Flame）支持

### ISSUE THREAD

**Issue by WinExp** [msnx/KernelSU-Pixel4XL#5]
麻烦问问您这个内核支不支持Pixel4（Flame）啊，眼馋 KernelSU 好久了...

**Comment by msnx** [comment]
![image](https://user-images.githubusercontent.com/50575648/230566244-74f7479a-a6ff-4611-b8dc-769bc688bebc.png)

**Comment by msnx** [comment]
本仓库boot.img是参考官方文档构建的，原则上Pixel4（flame）和Pixel4XL（coral）使用的是同一套内核源码。但是目前我只有一台Pixel4XL设备用于验证img稳定性，建议审慎使用仓库镜像。

**Comment by jksalva42** [comment]
I am using that kernel in pixel 4 (flame) only no issues you can use also...
